# printk() enable for console output
# CONFIG_PRINTK=y

# Enable Logging
CONFIG_LOG=y

# Enable Sensor
CONFIG_SENSOR=y
CONFIG_DHT=y

# Enable floating point support
CONFIG_CBPRINTF_FP_SUPPORT=y

# Enable GPIOS
CONFIG_GPIO=y
