# printk() enable for console output
# CONFIG_PRINTK=y

# Enable Logging 
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable GPIOS
# CONFIG_GPIO=y

# Enable I2C 
CONFIG_I2C=y

# Display subsystem 
CONFIG_DISPLAY=y

# Display Driver (The SSD1306 driver supports even SH1106) 
CONFIG_SSD1306=y

# Enable Framebuffer
CONFIG_CHARACTER_FRAMEBUFFER=y

# Enable Heap Memory Allocation 
CONFIG_HEAP_MEM_POOL_SIZE=16384

# ADC and sensor subsystem
CONFIG_ADC=y
CONFIG_SENSOR=y

# Floating point printing support
CONFIG_CBPRINTF_FP_SUPPORT=y

# Give main thread more memory for floating-point string operations
CONFIG_MAIN_STACK_SIZE=4096
