# printk() enable for console output
# CONFIG_PRINTK=y

# Enable Logging 
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable GPIOS
CONFIG_GPIO=y

# Sensor subsystem 
CONFIG_SENSOR=y

# HC-SR04
CONFIG_HC_SR04=y

# Floating point support 
CONFIG_CBPRINTF_FP_SUPPORT=y
