# printk() enable for console output
CONFIG_PRINTK=y

# Enable GPIOS
CONFIG_GPIO=y

# Enable Logging 
CONFIG_LOG=y

# Enable I2C 
CONFIG_I2C=y

# Enable Floating point formatting
CONFIG_CBPRINTF_FP_SUPPORT=y
