# printk() enable for console output
# CONFIG_PRINTK=y

# Enable Logging 
CONFIG_LOG=y

# Enable GPIOS
# CONFIG_GPIO=y

# ENable Hardware Flash driver
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y

# Enable the flash map and the NVS subsystems
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
