# printk() enable for console output
# CONFIG_PRINTK=y

# Enable Serial console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable Logging 
CONFIG_LOG=y

# Force threads to print immediately, bypassing log thread
CONFIG_LOG_MODE_IMMEDIATE=y


# Enable GPIOS
# CONFIG_GPIO=y

# Enable Time slicing 
CONFIG_TIMESLICING=y

# Set the time slice size to 10 milliseconds 
CONFIG_TIMESLICE_SIZE=10

# Apply time slicing to all threads at Priority 5 and below
CONFIG_TIMESLICE_PRIORITY=5
